.TH GMAC 1
.SH "NAME"
gmac \- Microcode and Macrocode Compiler for TkGate
.SH "SYNOPSIS"
.B gmac
[\-o file] [files]

.SH "DESCRIPTION"
\fIgmac \fR is a microcode and macrocode compiler for tkgate.  More complete
documentation can be found at:
.PP
http://www.cs.cmu.edu/~hansen/tkgate

.SH "OPTIONS"
The options are as follows:
.TP 15
\-o file
Specifies the output file.

.SH "SEE ALSO"
tkgate(1), verga(1)


.SH "AUTHOR"
Jeffery Hansen (hansen@cmu.edu)

.SH "COPYRIGHT"
Copyright (c) 1999-2004 by Jeffery Hansen
